depend: [ShinyBase, PermissionsEx, AdminCmd]
softdepend: [BanReport, ProtocolLib, Vault]
name: ShinyBridge
main: com.hotmail.shinyclef.shinybridge.ShinyBridge
version: 1.1.1
commands:
    rolydplus:
        description: Gives access to bridge commands.
        usage: /<command> help
        aliases:
        - r+
        - rplus