depend: [ShinyBase]
softdepend: [BanReport, ProtocolLib]
name: ShinyBridge
main: com.hotmail.shinyclef.shinybridge.ShinyBridge
version: 0.0.6
commands:
    rolydplus:
        description: Gives access to bridge commands.
        usage: /<command> help
        aliases:
        - r+
        - rplus