depend: [ShinyBase, PermissionsEx]
softdepend: [BanReport, ProtocolLib]
name: ShinyBridge
main: com.hotmail.shinyclef.shinybridge.ShinyBridge
version: 1.0.1
commands:
    rolydplus:
        description: Gives access to bridge commands.
        usage: /<command> help
        aliases:
        - r+
        - rplus